import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Todo() {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-sm-7">
            <h1 className="text-center mb-3">Todo App</h1>
              <form action="">
                <div className="mb-3">
                  <input
                    type="title"
                    className="form-control"
                    placeholder="Type..."
                  />
                </div>
                <div className="text-end">
                  <button type="submit" className="btn btn-primary">
                    Save
                  </button>
                </div>
              </form>

              <table className="table table-bordered mt-4">
                <thead>
                  <tr>
                    <th>No.</th>
                    <th>Title</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
